wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.19
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.7
    t:
      1:
      - 1
      - 5
      - 9
      2:
      - 1
      - 5
      - 9
      4: 3.8.7
      5: 0.10.19
batch_size:
  desc: null
  value: 256
clustering_method:
  desc: null
  value: gmm-full
dataset:
  desc: null
  value: fmnist
device:
  desc: null
  value: cuda
epochs:
  desc: null
  value: 50
hid_dim:
  desc: null
  value: 10
layer1:
  desc: null
  value: 512
layer2:
  desc: null
  value: 512
layer3:
  desc: null
  value: 2048
lr:
  desc: null
  value: 0.0016751916797300658
n_neurons:
  desc: null
  value:
  - 784
  - 512
  - 512
  - 2048
  - 10
