program: train_vade.py
project: "VADE"
method: random
metric:
  name: ACC
  goal: maximize
parameters:
  dataset:
    value: mnist
  pretrained_model_file:
    value: "AE clustering/n3jkdalz/checkpoints/epoch=299-step=5999.ckpt"
  init_gmm_file:
    value: "saved_gmm_init/n3jkdalz/gmm-full-acc=0.78.pkl"
  multivariate_latent:
    value: False
  rank:
    value: 1
  lr:
    min: 0.001
    max: 0.003
  epochs:
    value: 100
  batch_size: 
    value: 256
  covariance_type: 
    values: [full]
