program: train_vade.py
project: "VADE"
method: random
metric:
  name: ACC
  goal: maximize
parameters:
  dataset:
    value: mnist
  pretrained_model_file:
    value: "AE clustering/2j41m899/checkpoints/epoch=99-step=7899.ckpt"
  init_gmm_file:
    value: "saved_gmm_init/2j41m899/gmm-full-acc=0.91.pkl"
  multivariate_latent:
    value: False
  rank:
    value: 1
  lr:
  value: 0.002
    # min: 0.001
    # max: 0.003
  epochs:
    value: 300
  data_size:
    value: 20000
  data_random_state:
    value: 42
  batch_size: 
    value: 256
  covariance_type: 
    values: [full]
