program: train_simple.py
project: "AE-clustering"
method: random
metric:
  name: ACC
  goal: maximize
parameters:
  hid_dim:
    value: 10
  lr:
    min: 0.0002
    max: 0.0005
          #    distribution: log_uniform
          #    min: -9.1
          #    max: -6.5
  epochs:
    values: [100, 200, 300]
  batch_size: 
    value: 256
  clustering_method: 
    values: [gmm-full]
  dataset:
    value: mnist
  data_size:
    value: 10000 
  data_random_state:
    value: 42
