program: train_triplets.py
project: "VaDE Triplets"
method: random
metric:
  name: ACC
  goal: maximize
parameters:
  pretrained_model_file:
    # value: pretrained_models/prime-night-30/autoencoder-epoch=29.ckpt
    value: "AE clustering/5wn5ybl3/checkpoints/epoch=69-step=16449.ckpt"
  lr:
    min: 0.001
    max: 0.003
  epochs:
    value: 50
  # triplet_loss_alpha_kl:
  #   distribution: log_uniform
  #   min: -2
  #   max: 2
  # triplet_loss_margin_kl:
  #   min: 0
  #   max: 50
  triplet_loss_alpha_kl:
    value: 0.0
  triplet_loss_alpha: 
    value: 0.0
    # distribution: log_uniform
    # min: 2
    # max: 6
  triplet_loss_margin: 
    min: 0.1
    max: 1.
  batch_size: 
    value: 256
  covariance_type: 
    values: [full]
