program: train_vade.py
project: "VADE"
method: uniform
metric:
  name: ACC
  goal: maximize
parameters:
  dataset:
    value: mnist
  data_size:
    value: 2000
#  pretrained_model_file:
#    value: "AE clustering/n3jkdalz/checkpoints/epoch=299-step=5999.ckpt"
#  init_gmm_file:
#    value: "saved_gmm_init/n3jkdalz/gmm-full-acc=0.78.pkl"
  multivariate_latent:
    value: False
#  rank:
#    value: 1
  lr:
    value: 0.002
  epochs:
    value: 300
  batch_size: 
    value: 64
  covariance_type: 
    values: [diag]
  seed:
    values: [42, 666, 117]
