program: train_simple.py
project: "AE clustering"
method: random
metric:
  name: ACC
  goal: maximize
parameters:
  hid_dim:
    value: 10
  lr:
    distribution: log_uniform
    min: -10
    max: -6
  epochs:
    values: [50, 70, 100]
  batch_size: 
    value: 256
  clustering_method: 
    values: [gmm-full]
  dataset:
    value: mnist
  data_size:
    value: 20000
  data_random_state:
    value: 42
